name: Labeler
on:
  pull_request:
    branches:
      - master
jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          echo steps.files.outputs.all
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done