name: Labeler
on:
  pull_request:
    branches:
      - master
jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - uses: lykahb/paths-filter@v2
        id: filter
        with:
          stat: json
          filters: |
            changed:
              - '**'
      - name: Remove Label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: single-line-change-in-contributors-md-file
      - name: Add Label
        id: label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.changed-files.outputs.all_changed_files == 'Contributors.md' }}
        with:
          labels: single-line-change-in-contributors-md-file
      - name: Print 'changed_files'
        run: echo ${{steps.filter.outputs.changed_files }}
      - name: Print 'additions'
        run: echo ${{fromJson(steps.filter.outputs.stat).changed.additionCount }}
      - name: Print 'deletions'
        run: echo ${{fromJson(steps.filter.outputs.stat).changed.deletionCount }}
