name: Labeler
on:
  pull_request:
    branches:
      - master
jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Label
        id: label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.changed-files.outputs.all_changed_files == 'Contributors.md' }}
        with:
          labels: |
            change-in-contributors-md-file
